# Generated by Django 3.1.5 on 2021-01-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210105_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='chapter',
        ),
        migrations.AddField(
            model_name='article',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='book.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='book.chapter'),
        ),
    ]
