# Generated by Django 3.1.5 on 2021-01-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210110_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='serial_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='serial_number',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='serial_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
