# Generated by Django 3.1.5 on 2021-01-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210111_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='serial_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='serial_number',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
