# Generated by Django 3.1.5 on 2021-01-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210111_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_index',
            field=models.TextField(blank=True, null=True),
        ),
    ]
